### DISCUSSION TITLE
full-text search limit 50 /w local docker db

### DISCUSSION THREAD

**Discussion by TwistedTransistor** [open-discourse/open-discourse#60] [Q&A] [answered]
I did set up the od db local after the readme.md instructions from the main od folder. Everything is working so far, after doing sh setup.sh and sh build.sh etc. But somehow the http://localhost:3000/?contentQuery still max out at **50** results. I did rebuild the db with the python src multiple times.
So the questions are: Did I miss something obvious and where in the process it sets up a full-text search limit.  

Sorry if this is not the right place to ask sth. like this.

**Comment by JabobKrauskopf** [comment, marked as answer]
In the [docker-compose](https://github.com/open-discourse/open-discourse/blob/main/docker-compose.yml) file, you have to add the `QUERY_LIMIT` environment variable to the proxy service. At the moment, the query limit defaults to 50 (I will definitely increase this limit in the next release). That's why you only see 50 results.
Your proxy service should then look something like this:
```yml
proxy:
    container_name: od-proxy
    build: proxy
    volumes:
      - ./proxy/package.json:/srv/package.json
      - ./proxy/yarn.lock:/srv/yarn.lock
      - ./proxy/src/:/srv/src/
    environment:
      - GRAPHQL_ENDPOINT=http://od-graphql:5000/graphql
      - CACHE_EXPIRATION=1000
      - QUERY_LIMIT=500
    depends_on:
      graphql:
        condition: service_started
    ports:
      - "5300:5300"
```
You should then see 500 results. You can increase the limit as you like.

Hope this answers your question :)
